export const SuccessMessage = {
	BRAND_CREATED: "Brand Created Successfully",
	SERVICE_CREATED: "Service Created Successfully",
	TICKET_CREATED: "Ticket Created Successfully",
	USER_INSERTED: "User Inserted Successfully",
	PASSWORD_UPDATED: "Successfully updated the password.",
	LOGIN: "User logged in successfully.",
	LOGOUT: "User logged out successfully",
	USER_LIST: "Successfully fetched user list",
	USER_BY_ID: "Successfully fetched user",
	SERVICE_BY_ID: "Successfully fetched service",
	USER_DETAIL_UPDATED: "Successfully updated user details",
	BRAND_LIST: "Successfully fetched brand list",
	SERVICE_LIST: "Successfully fetched service list",
	TICKET_LIST: "Successfully fetched ticket list",
	SERVICE_UPDATE: "Service Updated Successfully ",
	BRAND_UPDATE: "Brand Updated Successfully ",
	PAYMENT_DETAIL_SAVED: "Payment detail saved Successfully ",
	FOLLOWUP_SAVED: "Follow_up saved Successfully ",
};
