export const SuccessMessage = {
    'ALERT_UPDATED': 'Alert Updated Successfully',
    'DATA_UPDATED': 'Data Updated',
    'OTP_SEND_SUCESSFULLY': 'OTP Sent successfully',
    'MOBILE_NUMBER_UPDATED_SUCESSFULLY': 'Mobile Number updated successfully',
    'EMAIL_ID_UPDATED_SUCESSFULLY': 'Email Id updated successfully',
    'MAIL_SENT': 'Email sent for verification, please check your email and verify',
    'USER_INSERTED': 'User Inserted Successfully',
    'PASSWORD_UPDATED': 'Successfully updated the password.',
    'FETCHED_SESSIONS': 'Successfully fetched the sessions.',
    'LOGIN': 'User logged in successfully.',
    'LOGOUT': 'User logged out successfully',
    'USER_LIST': 'Successfully fetched user list',
    'USER_DETAIL_UPDATED': 'Successfully updated user details',
}